### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble-collections#1]
@doowb should we come up with a different name? looks like this is generic enough to be named something else. (I know I suggested the name! ;-)

**Comment by doowb** [comment]
I know... Maybe we can make it something like `related-lists` since it basically handles a collection of related lists.

**Comment by jonschlinkert** [comment]
hmmm let me think on that one

**Comment by doowb** [comment]
Closing. This was refactored to be an assemble plugin that adds middleware and helpers for working with collections described in front-matter.
