### ISSUE TITLE
Move logic from Assemble to this repo

### ISSUE THREAD

**Issue by doowb** [assemble/assemble-collections#2]
Move a lot of the [core-collections](https://github.com/assemble/assemble/blob/v0.5.0/lib/plugins/core-collections.js) logic from Assemble to this repo since it can be generalized.

I'd like to see the following:
- [ ] Retrieve sorted list of collection Items as Array
- [ ] Retrieve all / each collection item with sorted list of related items as Array
- [ ] Pass in options / config to set sorting properties before generating collections. This will allow easily retrieving collections by name and from loops in template languages like Handlebars.
- [ ] Generate pagination objects for collections and related items lists.

**Comment by doowb** [comment]
Due to assemble refactoring this is no longer needed.

**Comment by jonschlinkert** [comment]
should we refactor this be helpers or plugins for working with the native collections? or just deprecate it and add a message to the readme?

**Comment by doowb** [comment]
I was thinking that refactoring it to be helpers and plugins would be useful. It could enable the "old style" collections where the front-matter determines which "collection" a view is in. Basically, creating a data object that can be used in templates. (These could also be template collections internally for code-reuse).

**Comment by jonschlinkert** [comment]
good ideas, sounds like the right approach
